version: "3.3"
services:
  app:
    image: ghcr.io/ditsi/impulse:<release_tag>
    environment:
      SLACK_BOT_USER_OAUTH_TOKEN: <slack_bot_user_oauth_token>
      SLACK_VERIFICATION_TOKEN: <slack_verification_token>
      MATTERMOST_ACCESS_TOKEN: <mattermost_access_token>
      CONFIG_PATH: "/config"
      DATA_PATH: "/data"
    volumes:
    - ./data:/data
    - ./config:/config
    ports:
    - "127.0.0.1:5000:5000"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 500M
    restart: unless-stopped
