version: "3.3"
services:
  detweet:
    image: ghcr.io/ditsi/impulse:main # Do not use 'main'! Use tag from here https://github.com/DiTsi/impulse/tags
    environment:
      SLACK_BOT_USER_OAUTH_TOKEN: <slack_bot_user_oauth_token>
      SLACK_VERIFICATION_TOKEN: <slack_verification_token>
      MATTERMOST_ACCESS_TOKEN: <mattermost_access_token>
      CONFIG_PATH: "/config"
      DATA_PATH: "/data"
    volumes:
    - ./data:/data
    - ./config:/config
    ports:
    - 5000:5000
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 500M
