name: staging

concurrency:
  group: ${{ github.ref }}

on:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-20.04
    permissions:
      contents: read
      packages: write
    steps:

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: /Log in to the Container registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: 'ghcr.io/eslupmi/impulse:release'

  deploy-to-staging:
    needs: build-and-push-image
    runs-on: ubuntu-20.04
    steps:
      - name: Recreate IMPulse
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.STAGING_HOST }}
          username: ${{ secrets.STAGING_USER }}
          key: ${{ secrets.STAGING_SSH_KEY }}
          script: |
            cd /opt/impulse/staging/slack
            docker-compose pull
            docker-compose up -d
            
            cd /opt/impulse/staging/mattermost
            docker-compose pull
            docker-compose up -d
